#!system for system strings
#!victory for victory reasons
#!counter for counter names
#!setname for archetype names
any line that doesn't start with the above keywords is ignored

#Custom Counters
!counter 0x1999 HP Counter
!counter 0x1998 Mana Counter
!counter 0x1997 Action Counter
!counter 0x1996 Job Energy
!counter 0x1995 Magic Reduction
!counter 0x1994 Poison Counter
!counter 0x1993 Physical Reduction
!counter 0x1992 Berserker Counter
!counter 0x1991 Disable Counter
!counter 0x1990 Command Counter


#Custom Archetype
!setname 0xf20 FFCCG
!setname 0xf21 Mecha Phantom Commander
!setname 0x2045 Imprisoned Archfiend